---
dokuwiki_urls:
  - wiki2.realraum.at
  - doku.realraum.at
#  - wiki.realraum.at
#  - w.r3.at

dokuwiki_plugins:
  diagram:
    url: http://nikita.melnichenko.name/download.php?q=dokuwiki-diagram-latest.tgz
    sha256: c303704123fefbf00be94fa31ed4ed541c419e8375ba0a1295e8235077ba42e6
  icons:
    url: https://github.com/giterlizzi/dokuwiki-plugin-icons/archive/refs/heads/master.tar.gz
    sha256: e77aacc88b058f94bfa3f1d3099339f1e0ab56a0828e9fa5cb895373eeb29b10
  move:
    url: https://github.com/michitux/dokuwiki-plugin-move/archive/refs/tags/2025-06-09.tar.gz
    sha256: 08c451bb7313bfbfa378f0f49df0cb6ec87c304ff692ed0a377a42272b7a5d23
  include:
    url: https://github.com/dokufreaks/plugin-include/archive/master.tar.gz
    sha256: d73b9d833b10179c5c807175f32c3aef154fddce49095e21c4ee89a4664b5338
  pagelist:
    url: https://github.com/dokufreaks/plugin-pagelist/archive/master.tar.gz
    sha256: 1257a39f6c9a8fd5fca5726b9a4c7604b6decfa1177d887a287e7d41261a3e4f
  tag:
    url: https://github.com/dokufreaks/plugin-tag/archive/master.tar.gz
    sha256: 2ec1305c7e31954f3206a85bf6cd797871d8695e9eb0d67be553abe1df170dd8
  wrap:
    url: https://github.com/selfthinker/dokuwiki_plugin_wrap/archive/refs/tags/stable.tar.gz
    sha256: 060d72e664595c746616f1b552213ec615bcb3132e762b2d8a24f672fdd048c0
  multiorphan:
    url: https://github.com/i-net-software/dokuwiki-plugin-multiorphan/archive/refs/tags/2021-12-20.tar.gz
    sha256: bd8b4d81955714620773e0c884295673d496cc690e38b3aa1fbd70ea3b219205

dokuwiki_templates:
  bootstrap3:
    url: https://github.com/giterlizzi/dokuwiki-template-bootstrap3/archive/refs/tags/v2025-06-13.tar.gz
    sha256: d0aea1b8c5846012ee4ba6968921d97cb88b8d54eb062c62ce01a6d15a00714d
    # url: 'https://github.com/dokuwiki/dokuwiki/releases/download/release-2025-05-14a/dokuwiki-2025-05-14a.tgz'
    # sha256: '91e508832febe10c7317e484e946576692bf9181397f8dace1df006f8161176d'

dokuwiki_config:
  title: "realraum"
  startpage: "realraum"
  template: "bootstrap3"
  tagline: "Hackspace in Graz"
  sidebarpage: "sidebar"
  license: "cc-by-sa"
  savedir: "/srv/dokuwiki/data"
  recent: 50
  recent_days: 21
  breadcrumbs: 0
  fullpath: 1
  dformat: '%Y-%m-%d %H:%M'
  sneaky_index: 1
  useacl: 1
  passcrypt: 'bcrypt'
  superuser: '@admin'
  disableactions: 'register'
  mailguard: 'hex'
  htmlok: 1
  mailfrom: 'noreply@wiki.realraum.at'
  sitemap: 5
  dnslookups: 0

