---
sshd_allowusers_host:
  - spaceapi

r3status_spaceapi_path: /dev/shm/spaceapi
r3status_ics_path: /dev/shm/ics
r3status_spaceapi_update_user_ssh_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDcwqg/oohCV3sTFHODBPUViOaGsoKL2Vp5suNAdLFJz4pdhfH7n4eXzI/3Ork6mDrDZ8XNmDq9g6jERweWQmS37THL33N2RmyDFfpwyQog/pzvEB6U0BGE6VN2zmgmrmvVZNdhKh/E74dM/22abAt32I6xSJi8C2CfVshHaFzNAV8N4lmGMGi0QXNMkAZDaYG0iptRuZOoZarCkfRybyh8pFkHt4Hl/tWocMOihI1KsWtbIgRUdTTpGMXmxMd0k2t9am+NxiUlBIRE8aEc4nTqcZTqullddEAGoksuUCLc0yYbFCzpTkZ1lrU5+oQhZyPWgnJ7s2yK7M2luBSAle8T realraum@smsgw.realraum.at

r3status_www_content:
  url: 'https://github.com/realraum/infokiosk/archive/05d38c5593f3cc4f22a726e0c392e59e19400c85.tar.gz'
  sha256: 'a421de6c40ecbfde6318aa3e6f8ac2a5ba42a5b37f40bb1c08c9784aff367b71'


acmetool_directory_server: "{{ acmetool_directory_server_le_live }}"

