---
sshd_allowusers_host:
  - spaceapi

r3status_spaceapi_path: /dev/shm/spaceapi
r3status_ics_path: /dev/shm/ics
r3status_spaceapi_update_user_ssh_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDcwqg/oohCV3sTFHODBPUViOaGsoKL2Vp5suNAdLFJz4pdhfH7n4eXzI/3Ork6mDrDZ8XNmDq9g6jERweWQmS37THL33N2RmyDFfpwyQog/pzvEB6U0BGE6VN2zmgmrmvVZNdhKh/E74dM/22abAt32I6xSJi8C2CfVshHaFzNAV8N4lmGMGi0QXNMkAZDaYG0iptRuZOoZarCkfRybyh8pFkHt4Hl/tWocMOihI1KsWtbIgRUdTTpGMXmxMd0k2t9am+NxiUlBIRE8aEc4nTqcZTqullddEAGoksuUCLc0yYbFCzpTkZ1lrU5+oQhZyPWgnJ7s2yK7M2luBSAle8T realraum@smsgw.realraum.at

r3status_www_content:
  url: 'https://github.com/realraum/infokiosk/archive/c2571da52f5c68d11d8d2e2d00a4580aea7b83e7.tar.gz'
  sha256: '406844afd3ebc483ddbfc06a398182566579b9be0b935f83bcacfd2479cc54f5'


acmetool_directory_server: "{{ acmetool_directory_server_le_live }}"

ssmtp_root: postmaster
ssmtp_mailhub: 89.106.215.28 #aka vex1
ssmtp_hostname: vex2.realraum.at
smtp_from_line_override: YES
# ssmtp_auth_user:
# smtp_auth_pass:
# ssmtp_use_starttls:
