---
- name: Basic Setup for vex2
  hosts: vex2
  roles:
  - role: base
  - role: dirty-hacks/vex2-base
  - role: acmetool/base
  - role: nginx
  - role: web/realraumat
  - role: web/r3redirects
  - role: web/dokuwiki
  - role: web/r3status
